### ISSUE TITLE
how to find download files link?

### ISSUE THREAD

**Issue by direcee** [jsplumb-toolkit-demonstrations/vue2-flowchart-builder#1]
"jsplumbtoolkit": "file:./jsplumbtoolkit.tgz",
    "jsplumbtoolkit-vue2": "file:./jsplumbtoolkit-vue2.tgz",
    "jsplumbtoolkit-drop": "file:./jsplumbtoolkit-drop.tgz",
    "jsplumbtoolkit-vue2-drop": "file:./jsplumbtoolkit-vue2-drop.tgz",
    "jsplumbtoolkit-undo-redo": "file:./jsplumbtoolkit-undo-redo.tgz",
    "jsplumbtoolkit-syntax-highlighter": "file:./jsplumbtoolkit-syntax-highlighter.tgz",
    "jsplumbtoolkit-demo-support": "file:./jsplumbtoolkit-demo-support.tgz",
    "jsplumbtoolkit-editable-connectors": "file:./jsplumbtoolkit-editable-connectors.tgz",

**Comment by sporritt** [comment]
You have to either be a Toolkit licensee or evaluator.
